title: Reboot - Pfingsjugendtreffen
baseurl: ""
url: "http://reboot.silas.im"
author:
    name: EC Pfalz
    webmaster: Silas Krause
github_username:  sil4s
sass:
    sass_dir: _sass
    style: compressed

exclude: [2014, coming_soon]
