title: Reboot - Pfingsjugendtreffen
baseurl: ""
url: "http://reboot.ec-pfalz.de"
author:
    name: EC Pfalz
    webmaster: Silas Krause
github_username:  krsilas
sass:
    sass_dir: assets/css/
    style: compressed
exclude: [assets/img/resources]
