title: Reboot - Pfingsjugendtreffen
baseurl: ""
url: "http://reboot.ec-pfalz.de"
author:
    name: EC Pfalz
    webmaster: Silas Krause
github_username:  sil4s
sass:
    sass_dir: _sass
    style: compressed
exclude: [assets/img/resources]
